### ISSUE TITLE
Infinite error loop after upgrade to 1.46.0

### ISSUE THREAD

**Issue by TSIA-SN** [segmentio/analytics-next#705]
After upgrading to 1.46.0, our page gets stuck in an infinite error loop due to resolveLoadStart being undefined https://github.com/segmentio/analytics-next/blob/b3350968a5437f5c824315aaa15602d648c1ac4e/packages/browser/src/browser/index.ts#L338

We're using NextJS 12.1.0 on Node 16.18.1 and the problem only happens when the source is built and run (`npm run build` followed by `npm run start`) and displays as `TypeError: g is not a function` (where `g` is the alias for resolveLoadStart) in the browser console . If the site is run in dev mode with `npm run dev` or if WebPack's `config.optimization.minimize` is set to `false` in next.config.js it works fine.

We are using the example code from https://github.com/segmentio/analytics-next/tree/master/packages/browser#using-react-advanced-w-react-context to set up our Segment Context. I tried updating the code to this, which should technically be the same, and it also has the issue:
```
const analytics = useMemo(
  () => {
   const analyticsBrowser = new AnalyticsBrowser();
   analyticsBrowser.load({ writeKey });
   return analyticsBrowser;
  },
  [writeKey]
);
```

The error does not exist in 1.45.0. Are there a 1.46.0 migration steps we need to take?

**Comment by silesky** [comment]
@TSIA-SN, we actually have a NextJS 12.1.0 example: https://github.com/segmentio/analytics-next/tree/master/examples/with-next-js.

I just tested it by running `yarn build && yarn start` and it works as expected. Would you be able to share a minimal example repo where you can reproduce the error?

**Comment by TSIA-SN** [comment]
I've been unable to get the example project to build on my machine, though I noticed it's using node `14.15.0` instead of `16.18.1`, so I am curious whether that makes a difference.

Here's my next.config.js (with some non-vital strings removed).

```
require('dotenv').config({ path: '../../.env' });
const { basePaths } = require('config/app/config');
const { withAxiom } = require('next-axiom');

const path = require('path');
const withTM = require('next-transpile-modules')(['ui', 'utils']);

module.exports = withAxiom(
  withTM(
    {
      basePath: '<basePath>',
      eslint: {
        // Warning: This allows production builds to successfully complete even if
        // your project has ESLint errors.
        ignoreDuringBuilds: true,
      },
      reactStrictMode: true,
      swcMinify: true,
      images: {
        domains: ['images.ctfassets.net'],
      },
      sassOptions: {
        includePaths: [path.join(__dirname, 'styles')],
        camelCase: true,
      },
      experimental: {
        images: { layoutRaw: true },
      },
      webpack(config) {
        config.module.rules.push({
          test: /\.svg$/,
          use: ['@svgr/webpack'],
        });

        return config;
      },
    },
    { debug: true }
  )
);
```

**Comment by silesky** [comment]
> I've been unable to get the example project to build on my machine, though I noticed it's using node 14.15.0 instead of 16.18.1, so I am curious whether that makes a difference.

It shouldn't make a difference. Make sure to run `yarn install && yarn build` at the root of the monorepo, so you can build the monorepo's dependencies!

**Comment by silesky** [comment]
Assume resolved. Please re-open if you run into trouble.
